<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHL0WMUE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHL0WMUE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHL0WMUE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHL0WMUE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHL0WMUE\App_KernelDevDebugContainer([
    'container.build_hash' => 'HL0WMUE',
    'container.build_id' => 'b5924961',
    'container.build_time' => 1783372793,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHL0WMUE');
